@props(['size' => 56, 'mono' => false])

{{--
    The WorkForce mark — "Staff Cross": four members of the care team, head and
    shoulders, facing a shared patient at the centre, and together drawing the
    cross. Inline rather than an <img> so it stays crisp at every size, costs no
    request, and cannot be left pointing at a deleted file.

    Each figure is the same head (circle) and shoulders (a half-disc whose flat
    edge faces the centre), drawn once pointing up and turned a quarter at a
    time. The turns are written out rather than done with <use>, because this
    component appears several times on one page and <use> needs an id.

    The figures paint in currentColor, so the colour belongs to the context that
    places the mark — navy on a light page, white on the sidebar's gradient.
    The centre dot is the one fixed accent (--hr-brand-dot, orange); pass
    `mono` for the one-colour print version, where it follows currentColor too.

    The app-icon framing of the same drawing (on a navy tile) is in
    public/favicon.svg and the PNGs under public/images/icons, generated by
    scripts/generate-brand-icons.php.

    aria-hidden because the product name sits beside it everywhere it is used —
    a screen reader would otherwise announce the brand twice.
--}}
<svg
    {{ $attributes }}
    width="{{ $size }}"
    height="{{ $size }}"
    viewBox="0 0 64 64"
    fill="currentColor"
    aria-hidden="true"
    focusable="false"
>
    @foreach ([0, 90, 180, 270] as $turn)
        <g transform="rotate({{ $turn }} 32 32)">
            <circle cx="32" cy="6.5" r="4.5" />
            <path d="M24 19.5a8 6.5 0 0 1 16 0z" />
        </g>
    @endforeach
    <circle cx="32" cy="32" r="5" @unless ($mono) style="fill: var(--hr-brand-dot, #e8743b)" @endunless />
</svg>
