@extends('layouts.app')

@section('title', 'Audit Logs')

@section('content')
    <section class="page-heading workforce-heading"><div><p class="eyebrow">Security & Compliance</p><h1>Audit Logs</h1><p>Read-only history of authenticated write actions without passwords, tokens, or submitted values.</p></div><a class="btn btn-primary dashboard-action" href="{{ route('audit-logs.export', request()->query()) }}"><x-icon name="download" /> Export CSV</a></section>
    <section class="panel workforce-filter-panel"><form method="GET" action="{{ route('audit-logs.index') }}" class="workforce-filters"><label><span>User</span><select name="user_id"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(($filters['user_id'] ?? '') == $user->id)>{{ $user->name }}</option>@endforeach</select></label><label><span>Action contains</span><input name="action" value="{{ $filters['action'] ?? '' }}" placeholder="e.g. leaves.approve"></label><label><span>From</span><input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"></label><label><span>To</span><input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}"></label><button class="btn btn-primary">Apply filters</button></form></section>
    <section class="panel workforce-table-panel"><div class="panel-header"><div><p class="panel-kicker">Immutable activity trail</p><h2>Recorded write requests</h2></div><span class="history-caption">{{ $logs->total() }} events</span></div><div class="table-responsive"><table class="dashboard-table workforce-table"><thead><tr><th>Timestamp</th><th>User</th><th>Action</th><th>Request</th><th>Subject</th><th>IP</th><th>Status</th></tr></thead><tbody>
        @forelse($logs as $log)<tr><td>{{ $log->created_at->format('M j, Y g:i:s A') }}</td><td>{{ $log->user?->name ?? 'Unauthenticated' }}</td><td><strong>{{ $log->action }}</strong></td><td><code>{{ $log->method }} /{{ $log->path }}</code></td><td>{{ $log->subject_type ? class_basename($log->subject_type).' #'.$log->subject_id : '—' }}</td><td>{{ $log->ip_address ?? '—' }}</td><td><span @class(['audit-http-status','success'=>$log->response_status < 400,'failed'=>$log->response_status >= 400])>{{ $log->response_status }}</span></td></tr>@empty<tr><td colspan="7" class="empty-table-cell"><x-icon name="shield" /><strong>No audit records yet</strong><span>Write actions will be recorded automatically.</span></td></tr>@endforelse
    </tbody></table></div>@if($logs->hasPages())<div class="report-pagination">{{ $logs->onEachSide(1)->links('pagination::bootstrap-5') }}</div>@endif</section>
@endsection
