@php($editing = isset($room))
<fieldset class="organization-fieldset">
    <legend>Room details</legend>
    <label class="organization-field"><span>Room code</span><input type="text" name="code" maxlength="30" required value="{{ old('code', $room->code ?? '') }}" placeholder="OR-1">@error('code')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field"><span>Room name</span><input type="text" name="name" maxlength="150" required value="{{ old('name', $room->name ?? '') }}" placeholder="Operating Room 1">@error('name')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field"><span>Room type</span><select name="room_type" required>@foreach($types as $value => $label)<option value="{{ $value }}" @selected(old('room_type', $room->room_type ?? 'ward') === $value)>{{ $label }}</option>@endforeach</select>@error('room_type')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field"><span>Unit</span><select name="department_id" required><option value="">Select unit</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id', $room->department_id ?? null) == $department->id)>{{ $department->name }}</option>@endforeach</select><small>A room belongs to the unit that staffs it. It is a place, not a department of its own.</small>@error('department_id')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field"><span>Beds</span><input type="number" name="bed_capacity" min="1" max="500" value="{{ old('bed_capacity', $room->bed_capacity ?? '') }}" placeholder="Leave blank for a theatre or clinic"><small>Bedded rooms derive their staffing from beds and the unit's nurse-to-patient ratio.</small>@error('bed_capacity')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field"><span>Maximum staff</span><input type="number" name="max_staff" min="1" max="100" value="{{ old('max_staff', $room->max_staff ?? '') }}" placeholder="No ceiling"><small>The most people who can work in here at once. The board refuses to go past it.</small>@error('max_staff')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field"><span>Charge cover from rank</span><select name="min_seniority_rank" required>@foreach(App\Models\Position::SENIORITY_RANK_LABELS as $rank => $label)<option value="{{ $rank }}" @selected(old('min_seniority_rank', $room->min_seniority_rank ?? 1) == $rank)>{{ $rank }} — {{ $label }}</option>@endforeach</select><small>A theatre covered entirely below this rank cannot be published.</small>@error('min_seniority_rank')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field"><span>Status</span><select name="status" required>@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('status', $room->status ?? 'active') === $value)>{{ $label }}</option>@endforeach</select><small>Anything but active refuses new assignments until the room reopens.</small>@error('status')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-field organization-field-full"><span>Notes</span><textarea name="notes" maxlength="1000" placeholder="Equipment, access, or why this room is closed">{{ old('notes', $room->notes ?? '') }}</textarea>@error('notes')<small class="organization-error">{{ $message }}</small>@enderror</label>
    <label class="organization-checkbox organization-field-full"><input type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $room->is_active ?? true))><div><strong>Active room</strong><small>Active rooms appear on the room board and can be rostered into.</small></div></label>
</fieldset>
